### PR TITLE
zynqmp, ultra96v2: add linux images

### PR DESCRIPTION
**Pull request by chrisguikema**
This commit adds Petalinux-2021.1 prebuilt images for the zynqmp and ultra96v2 platforms.

### CODE REVIEW

**Comment by axel-h** [comment]
Please provide a `README.md` in each folder also with a bit if information, e.g. what the images are, where they come from or how to build them. See also the readme file in the other platform folder.

**Comment by lsf37** [comment]
> @lsf37 Any insight on how to get the License check to pass?

For files that don't allow inline comments, you can add a license and copyright to the [`.reuse/dep5`](https://github.com/seL4/camkes-vm-images/blob/master/.reuse/dep5) file of the same repo. You can also add a `filename.license` file in the same directory, which would usually be preferred, but in this repo, since there are a bunch of images, I think adding to the `dep5` file is nicer.

**Comment by chrisguikema** [comment]
Thanks, that was really straight forward!

**Comment by axel-h** [comment]
This PR looks ok now, but what is the merge criterion? There seems a ZCU102 board in CI, having this images now allows activation the VM tests. So passing at least the minimal VM example would be the goal?

**Comment by chrisguikema** [comment]
See my comment in https://github.com/seL4/camkes-vm/pull/42 for why a minimal example isn't yet feasible.

**Comment by chrisguikema** [comment]
@lsf37 @kent-mcleod what is the criteria to merge this? These images won't run until the SMC RFC is handled, so is it okay to let this sit? Or would it be better to merge, and then they'll be used in an example in the future?

**Comment by kent-mcleod** [comment]
> @lsf37 @kent-mcleod what is the criteria to merge this? These images won't run until the SMC RFC is handled, so is it okay to let this sit? Or would it be better to merge, and then they'll be used in an example in the future?

Maybe let them sit as they can't break due to other code changes

**Comment by axel-h** [comment]
Seems the files in the folders `ultra96v2` and `zynqmp` the same, can't we use just `zynqmp` here? It seems in https://github.com/seL4/camkes-vm-examples/pull/46 there is no reference to `ultra96v2` anyway, so at the moment this is then unused anyway?

**Comment by chrisguikema** [comment]
> Seems the files in the folders `ultra96v2` and `zynqmp` the same

They're different:

```
chrisguikema: ~/seL4/UPSTREAM/camkes-vm/projects/camkes-vm-images/ultra96v2/2021_1 [zynqmp_ultra96_support] $ md5sum linux rootfs-minimal.cpio.gz 
583ede6e15ce69093fd8800f9d229b8f  linux
a4b5352379915edd286b927d9c55d24e  rootfs-minimal.cpio.gz
chrisguikema: ~/seL4/UPSTREAM/camkes-vm/projects/camkes-vm-images/zynqmp/2021_1 [zynqmp_ultra96_support] $ md5sum linux rootfs-minimal.cpio.gz 
edbad6a15dded2b7e7ffc4aa9e91bfc8  linux
3c46cc201f3a96e007fa090d435b3205  rootfs-minimal.cpio.gz
```

The big difference with the Ultra96 is that the serial port is on the `ff010000` device. There's some files in the rootfs to allow the getty to default to the secondary serial port. But I understand that there isn't an example project for the ultra96 yet, so I can remove those images from this commit.

**Review by axel-h — APPROVED** [review]
Looks ok to me to merge this.

For the Ultra96 (where you removed the files) I am not sure how to handle it. It is a nice board actually, but unfortunately no longer available - so that puts it at a dead end somehow. But there is some support for this platform, so I think we could also merge these images then for more completness?

**Comment by chrisguikema** [comment]
Yeah, that's unfortunate about the U96. Though i'm sure there are other cheap development platforms that use the ZUS+ processor.

@lsf37 can this be merged?

**Review by lsf37 — APPROVED** [review]

**Pull request merged**
